#
-
note new: key("cmd-ctrl-n")
clipboard: key("cmd-alt-v")
kill: key("backspace")
junk: key("backspace")
clobber: key("alt-backspace")
destroy: key("cmd-backspace")
fly left: key("alt-left")
fly right: key("alt-right")
bobblehead: key("cmd-alt-f")
face: key("space")
spacer: key("space")
say sir: key("space")
moji: key("cmd-ctrl-space")
full screen: key("cmd-ctrl-m")
untab: key("shift-tab")
