desk <number_small>: user.desktop(number_small)
# JP custom desktop navigation
desk left: key("ctrl-left")
desk right: key("ctrl-right")
desk last: key("ctrl-left")
desk next: key("ctrl-right")
desk show: user.desktop_show()
window move desk <number>: user.window_move_desktop(number)
window move desk left: user.window_move_desktop_left()
window move desk right: user.window_move_desktop_right()
